image: cprov/stoq:candidate

services:
  - postgres:9.5

variables:
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

test:
  stage: test
  before_script:
    # Install stoqlib from master.
    - apt update
    - apt --yes install libcairo2-dev python3-pip python3-virtualenv libpq-dev libjpeg8-dev zlib1g-dev
    - export LC_ALL=pt_BR.UTF-8
    - python3 -m venv env
    - source env/bin/activate
    - pip install -U setuptools pip poetry wheel
    - poetry install
    - poetry shell
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stoqtech/private/stoq-plugin-ifood.git
    - pip install -e stoq-plugin-ifood --no-deps --no-build-isolation
    - python3 -V
    - poetry show
  script:
    - make coverage

.create_deb:
  stage: build
  before_script:
    - apt update
    - python --version
    - python2 --version
    # Install tools to create debian packages
    - apt --yes install libcairo2-dev python3-pip python3-virtualenv libpq-dev devscripts debhelper python3-all
    - export LC_ALL=pt_BR.UTF-8
    - rm -rf dist
    - cp setup_old.py setup.py
  script:
    - make deb
  artifacts:
    paths:
      - dist/*.deb

create_deb_master:
  extends: .create_deb
  only:
    - master

create_deb_manual:
  extends: .create_deb
  stage: test
  when: manual
