image: cprov/stoq:candidate

services:
  - postgres:9.5

variables:
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

test:
  stage: test
  before_script:
    # Install stoqlib from master.
    - apt update
    - apt --yes install libcairo2-dev python3-pip python3-virtualenv libpq-dev libjpeg8-dev zlib1g-dev swig
    - export LC_ALL=pt_BR.UTF-8
    - python3 -m venv env
    - source env/bin/activate
    - pip install -U setuptools pip wheel importlib-metadata==2.1.0
    - pip install -U poetry
    # providing credentials using poetry config http-basic or environment variables didn't work
    # (as suggested by poetry docs https://python-poetry.org/docs/repositories/)
    # so the workaround below becomes necessary so the CI job can download gitlab PyPI packages
    - sed -i 's|\(gitlab.com\)|__token__:'"${GITLAB_PYPI_TOKEN}"'@\1|' pyproject.toml
    - poetry install
    - poetry shell
    - python3 -V
    - poetry show
  script:
    - make coverage

.create_deb:
  stage: build
  before_script:
    - apt update
    - python --version
    # Install tools to create debian packages
    - apt --yes install libcairo2-dev python3-pip python3-virtualenv libpq-dev devscripts debhelper python3-all libjpeg8-dev zlib1g-dev swig
    - export LC_ALL=pt_BR.UTF-8
    - rm -rf dist
    - python3 -m venv env
    - source env/bin/activate
    - pip install -U setuptools pip wheel importlib-metadata==2.1.0
    - pip install -U poetry
    - make requirements.txt
    - sed -i 's|\(gitlab.com\)|__token__:'"${GITLAB_PYPI_TOKEN}"'@\1|' pyproject.toml
    - sed -i 's|\(gitlab.com\)|__token__:'"${GITLAB_PYPI_TOKEN}"'@\1|' requirements.txt
  script:
    - cp setup_old.py setup.py
    - cp debian/control_old debian/control
    - cp debian/rules_old debian/rules
    - make deb
  artifacts:
    paths:
      - dist/*.deb

create_deb_master:
  extends: .create_deb
  only:
    - master

create_deb_manual:
  extends: .create_deb
  stage: test
  when: manual

create_bundle_manual_xenial:
  extends: .create_deb
  script:
    - make bundle_deb
  stage: test
  when: manual

create_bundle_manual_bionic:
  image: romaia/stoq:bionic
  extends: .create_deb
  script:
    - make bundle_deb
  stage: test
  when: manual

create_bundle_manual_focal:
  image: romaia/stoq:focal
  extends: .create_deb
  script:
    - make bundle_deb
  stage: test
  when: manual


create_bundle:
  image: romaia/stoq:bionic
  extends: .create_deb
  script:
    - make bundle_deb
  only:
    - master

gitlab_pypi_upload:
  stage: test
  only:
    - master
  when: manual
  extends: .create_deb
  script:
    - poetry build
    - pip install -U twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine upload --skip-existing --repository-url "https://gitlab.com/api/v4/projects/13882298/packages/pypi" dist/*
