image: cprov/stoq:candidate

services:
  - postgres:9.5

variables:
  # Fetch utils/ submodule
  GIT_SUBMODULE_STRATEGY: recursive
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  STOQLIB_TEST_HOSTNAME: "postgres"
  STOQLIB_TEST_DBNAME: "test"
  STOQLIB_TEST_USERNAME: "test"
  STOQLIB_TEST_PASSWORD: ""

stages:
  - test
  - build

before_script:
  # Install stoqlib from master.
  - apt update
  - apt --yes install libcairo2-dev python3-pip
  - git clone https://github.com/stoq/stoq.git --depth 1
  - python3 -m pip install -U setuptools pip
  - python3 -m pip install pycairo
  - python3 -m pip install -e stoq --no-deps
  - python3 -m pip install -r requirements-test.txt
  - python3 -m pip install kiwi-gtk
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/stoqtech/private/stoq-plugin-ifood.git
  - python3 -m pip install -e stoq-plugin-ifood --no-deps
  - python3 -m pip freeze

test:
  stage: test
  script:
    - make coverage

.create_deb:
  stage: build
  script:
    # Install tools to create debian packages
    - apt update
    - python --version
    - python2 --version
    - apt --yes install devscripts debhelper python3-all
    - rm -rf dist
    - make deb
  artifacts:
    paths:
      - dist/*.deb

create_deb_master:
  extends: .create_deb
  only:
    - master

create_deb_manual:
  extends: .create_deb
  when: manual
